syntax = "proto3";

package dash.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "sphere/errors/errors.proto";

service AuthService {
  rpc LoginWithPassword(LoginWithPasswordRequest) returns (LoginWithPasswordResponse) {
    option (google.api.http) = {
      post: "/api/auth/login"
      body: "*"
    };
  }

  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {
    option (google.api.http) = {
      post: "/api/auth/refresh"
      body: "*"
    };
  }
}

message LoginWithPasswordRequest {
  string username = 1 [(buf.validate.field).required = true];
  string password = 2 [(buf.validate.field).required = true];
}

message LoginWithPasswordResponse {
  string access_token = 1 [json_name = "access_token"];
  string refresh_token = 2 [json_name = "refresh_token"];
  int64 expires_at = 3 [json_name = "expires_at"];
}

message RefreshTokenRequest {
  string refresh_token = 1 [
    json_name = "refresh_token",
    (buf.validate.field).required = true
  ];
}

message RefreshTokenResponse {
  string access_token = 1 [json_name = "access_token"];
  string refresh_token = 2 [json_name = "refresh_token"];
  int64 expires_at = 3 [json_name = "expires_at"];
}

enum AuthError {
  option (sphere.errors.default_status) = 500;

  AUTH_ERROR_UNSPECIFIED = 0;
  AUTH_ERROR_INVALID_CREDENTIALS = 1000 [(sphere.errors.options) = {
    status: 401
    reason: "INVALID_CREDENTIALS"
    message: "invalid username or password"
  }];
}
